import { GlobalStatePovider } from '_global/GlobalState'
import './globals.css'
import type { Metadata } from 'next'
import { Space_Mono } from 'next/font/google'
import Header from './_components/global/Header'
import Footer from '_sections/Footer'

const inter = Space_Mono({ subsets: ['latin'], weight: ['400', "700"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<GlobalStatePovider>
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  </GlobalStatePovider>)
}
