
import { Artwork } from "../types"

const artworks: Artwork[] = [
    {
        id: 0,
        src: "/images/new/1.png",
        title: "Artwork 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 3,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 2)),
        views: 123,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 1,
        src: "/images/new/2.png",
        title: "Artwork 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 1,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 456,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 2,
        src: "/images/new/3.png",
        title: "Artwork 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 2,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 789,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 3,
        src: "/images/new/5.png",
        title: "Artwork 5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 2,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 1213,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 4,
        src: "/images/new/6.png",
        title: "Artwork 6",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 3,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 1415,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 5,
        src: "/images/new/7.png",
        title: "Artwork 7",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 1,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 1617,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 6,
        src: "/images/new/8.png",
        title: "Artwork 8",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 2,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 1819,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 7,
        src: "/images/new/9.png",
        title: "Artwork 9",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc libero ultricies nunc, vitae ultricies nisl nisl vitae nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl. Sed vitae nisl auctor, ultricies nisl vitae, ultricies nisl.",
        artist: 3,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 2021,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 8,
        src: "/images/new/12.png",
        title: "Artwork 12",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus, nunc.",
        artist: 2,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 2627,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 9,
        src: "/images/new/13.png",
        title: "Artwork 13",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus.",
        artist: 2,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 2829,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 10,
        src: "/images/new/14.png",
        title: "Artwork 14",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus.",
        artist: 3,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 3031,
        tags: ["tag1", "tag2", "tag3"],
    },
    {
        id: 11,
        src: "/images/new/11.jpg",
        title: "Artwork 11",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec auctor, nisl eu ultricies dapibus.",
        artist: 1,
        createdAt: new Date(new Date().setFullYear(new Date().getFullYear() - 1)),
        views: 2425,
        tags: ["tag1", "tag2", "tag3"],
    },
]



export { artworks }